name: "restock_pilot"
version: "1.0.0"
config-version: 2

profile: "restock_pilot"

model-paths: ["models"]
test-paths: ["tests"]

models:
  restock_pilot:
    +schema: rp_analytics
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
